version: '3.8'

services:
  # Service Backend Node.js
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=overtime_db
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - app-network

  # Service Base de données MySQL
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=overtime_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # Service phpMyAdmin (optionnel, pour gérer la base de données)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge