version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=192.168.1.101
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=overtime_db;

  frontend:
    build: ./frontend
    ports:
      - "80:3000"
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=overtime_db;

    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: