version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_NAME=overtime_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_HOST=mysql
      - PORT=3000
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=overtime_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 