version: '3'
services:
  backend:
    image: boudrigakhaoula/overtime_backend:latest
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password123
      - DB_NAME=overtime_db
    depends_on:
      - db
  frontend:
    image: boudrigakhaoula/overtime_frontend:latest
    ports:
      - "80:80"
      command: npm run dev
    depends_on:
      - backend
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=overtime_db
    volumes:
      - db-data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Fichier local sur VM2

volumes:
  db-data: