FROM node:18
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . ./
# Assure que vite est installé et accessible
RUN npm install vite --save-dev
# Corrige les permissions
RUN chmod -R 755 /app/node_modules
# Utilise npx pour exécuter vite
CMD ["npx", "vite", "--host", "0.0.0.0"]