version: '3'
services:
  backend:
    image: boudrigakhaoula/overtime_backend:latest
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password123
      - DB_NAME=overtime_db
    depends_on:
      - db
  frontend:
    image: boudrigakhaoula/overtime_frontend:latest
    ports:
      - "80:5173"  # Vite utilise le port 5173 par défaut en dev
    command: npm run dev -- --host 0.0.0.0  # Lance Vite et expose l'application
    depends_on:
      - backend
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=overtime_db
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: